version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3020:8080
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3030:3030
